# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-19 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
